version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  chat-user:
    image: chat-user:latest
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - chat-network

  chat:
    image: chat:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - chat-user
    networks:
      - chat-network

  gateway:
    image: chat-gateway:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - chat
      - chat-user
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres_data:
